url: https://y7kim.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: SparklingGraph
email: riomus@gmail.com
description: "Sparkling graph is library that lets you to process your graphs in distributed manner. Library utlizes Spark and GraphX as computional backends."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Roman Bartusiak
  pic: 1
  position: 'Originator, Lead Developer'
  social:
    - title: twitter
      url: https://twitter.com/RomanBartusiak
    - title: github
      url: https://github.com/riomus

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/sparkling-graph

# Postal address (add as many lines as necessary)
address:
  - line: 'Wroclaw, Poland'

# Build settings
markdown: kramdown
permalink: pretty